### ISSUE TITLE
How to derive MagicFormat?

### ISSUE THREAD

**Issue by ghorn** [guibou/PyF#21]
Sometimes I have something like
```haskell
newtype Foo = Foo T.Text

foo :: Foo
foo = Foo "foo"

wow :: T.Text
wow = [f|blah blah {foo}|]
```
The error message is something like `No instance for (PyF.MagicFormat Foo)`.

Thinking I could write a `MagicFormat` instance for `Foo` I opened up the haddocks but `PyF` doesn't seem to expose it. Is there a way use `PyF` directly on custom datatypes?

Or is there a reason this shouldn't be allowed?

**Comment by guibou** [comment]
Thank you for reporting that.

I had always wondered how PyF can be extended to support formating of custom types. I have many options:

# Do nothing

Let people provide a custom formatter is the sub expression, such as `[f| foo = {show foo}|]`. It already works.

# Custom format string
 
Allow users to provide instance for a "custom format" type class which accept a format string. For example, we can imagine a type class such as:

```
class CustomFormat t where
     format :: String -> t -> String
```

The first argument being the formatting string from PyF. This works in python for example:

```
>>> import datetime
>>> d = datetime.date.today()
>>> f"{d:%Y-%m-%d}"
'2019-02-28'
```

This is highly convenient, but we may loose all the type checking guarantee of PyF for these types. Or we may extend PyF so that user can write their own type checker for the format string. I have no idea if that's possible / easy.

# Custom conversion and classification operator.

PyF internally classify the type in three categories:

- `Floating`, accepting anything of the `Floating` class
- `Integral`, accepting anything of the `Integral, Show` class (the `Show` constraint is here for some stupid reasons ;)
- `String`, accepting a few known string types (`Text`, `Builder` and `[Char]` and lazy variations)

We may exposes a type class which:

- Categorize the type
- Convert it to the right internal format (respectively `Double`, `Integer` and `String`).

This may be the best solution. The only issue is that it must be correctly designed because it will become part of the public API. For example, which are the right "internal" format. `Double` and `Integer` feels right, but `String` can be discussed.

# Use `Show` instance.

fallback to `Show` instance (perhaps explicitly) for all type which cannot be formatted.

@ghorn what will best suit your needs?

**Comment by ghorn** [comment]
Sounds like the right thing for the library is the custom conversion and classification. That sounds tricky though.

**Comment by guibou** [comment]
Actually classification and conversion already exits inside PyF, I just need to expose the type classes.

Is this a blocking feature for you? I'm currently working on a refactoring to improve on #18 and that one changes a bit the type classes. So if you are not in a hurry, I can finish my refactor and expose the new type classes. If you have a deadline, I'll change my priorities.

Please note that for now you can just use any formatting function directly in your expression. That's a bit more verbose for now, but works.

**Comment by guibou** [comment]
Actually, `MagicFormat` was removed in #32, but your issue is that you want to be able to format any input, not get any output. I'm reopening.

**Comment by guibou** [comment]
@Greg.

In your context, you can now use:

```
instance PyFToString Foo

type instance PyFClassify Foo = 'PyFString
```

First instance, `PyFToString` will tell how to convert `Foo` to string. Default implementation uses `Show` method.
Second instance, `PyFClassify` tells PyF which formatter to use by default, when using `[f|{Foo "bar"}|]` instead of `[f|{Foo "bar":s}|]`.
